// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHQldmSnqYixZRO6Gbsq6czMamMu1iris',
    appId: '1:731017054637:web:c4d3ac5ad6ddd5b4713924',
    messagingSenderId: '731017054637',
    projectId: 'update-b6343',
    authDomain: 'update-b6343.firebaseapp.com',
    storageBucket: 'update-b6343.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSwSJ_dUFRwHELHHAZFNr2vVURqVMQcY',
    appId: '1:731017054637:android:fa1bfde5dc0db7aa713924',
    messagingSenderId: '731017054637',
    projectId: 'update-b6343',
    storageBucket: 'update-b6343.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZsu8n9Rk1S3ZEiDsIxRxm2cf0UiOiFhk',
    appId: '1:731017054637:ios:da57a3e7bb285d78713924',
    messagingSenderId: '731017054637',
    projectId: 'update-b6343',
    storageBucket: 'update-b6343.appspot.com',
    iosClientId: '731017054637-kvkam77edjpp3n5ffg6m3tfjpphahlh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZsu8n9Rk1S3ZEiDsIxRxm2cf0UiOiFhk',
    appId: '1:731017054637:ios:da57a3e7bb285d78713924',
    messagingSenderId: '731017054637',
    projectId: 'update-b6343',
    storageBucket: 'update-b6343.appspot.com',
    iosClientId: '731017054637-kvkam77edjpp3n5ffg6m3tfjpphahlh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
